server:
  port: ${SERVER_PORT:9030}

spring:
  application:
    name: neo-services
  h2:
    console:
      enabled: true

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/PriceDB

spring.jpa:
    hibernate.ddl-auto: create-drop
#eureka:
#  client:
#    services-url: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka